export const ERROR_CODE = {
  FAILURE_TO_GET_GITHUB_ACCESS_TOKEN: 'FAILURE_TO_GET_GITHUB_ACCESS_TOKEN',
  FAILURE_TO_GET_GITHUB_USER: 'FAILURE_TO_GET_GITHUB_USER',
  INVALID_TOKEN: 'INVALID_TOKEN',
  LOGIN_REQUIRED: 'LOGIN_REQUIRED',
};
